name: Bug report
description: Create a report to help us improve
labels: ['bug']
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
    validations:
      required: true
  - type: textarea
    id: bug-affecting-who
    attributes:
      label: Who is the bug affecting
      description: Describe the stakeholders affected by this bug
    validations:
      required: true
  - type: textarea
    id: bug-affecting-what
    attributes:
      label: What is affected by this bug
      description: Describe the impact this bug is having
    validations:
      required: true
  - type: textarea
    id: bug-conditions
    attributes:
      label: When does this occur
      description: Describe the conditions under which the bug is occuring
    validations:
      required: true
  - type: textarea
    id: bug-replication
    attributes:
      label: How do we replicate this issue
      description: What are the steps to reproduce this behavior (use screenshots if applicable)
      value: |
        1. Do this...
        2. Then this...
        3. See error...
    validations:
      required: true
  - type: textarea
    id: bug-solution
    attributes:
      label: Expected behavior (i.e. solution)
      description: A clear and concise description of what you expected to happen
    validations:
      required: true
  - type: textarea
    id: bug-comments
    attributes:
      label: Other comments
      description: Add any other context about the problem here
    validations:
      required: false
