FROM ruby:2.5.1-alpine3.7 AS build-env
RUN apk update && apk add --no-cache build-base git
RUN gem update bundler
RUN mkdir -p /app
WORKDIR /app
COPY Gemfile Gemfile.lock ./
RUN bundle install -j 4
EXPOSE 4000
COPY . ./
CMD bundle exec jekyll serve -H 0.0.0.0 --verbose
VOLUME /app
