# are working against known samples
name: "OSCAL Validations: Integration tests"

# Triggered when code is pushed to master and on pull requests
on:
  push:
    branches:
      - master
      - develop
      - 'feature/**'  # This will match any branch starting with "feature"

  pull_request:

# the job requires some dependencies to be installed (including submodules), runs the tests, and then reports results
jobs:
  # one job that runs tests
  run-tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        cli_type: ['default', 'enhanced']
        include:
          - cli_type: default
            cli_url: https://repo1.maven.org/maven2/gov/nist/secauto/oscal/tools/oscal-cli/cli-core/1.0.3/cli-core-1.0.3-oscal-cli.zip
          - cli_type: enhanced
            cli_url: https://repo1.maven.org/maven2/dev/metaschema/oscal/oscal-cli-enhanced/2.4.0/oscal-cli-enhanced-2.4.0-oscal-cli.zip

    defaults:
        run:
          working-directory: ./build
    steps:
      # Check-out the repository under $GITHUB_WORKSPACE
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Set up Java
        uses: actions/setup-java@67fbd726daaf08212a7b021c1c4d117f94a81dd3
        with:
          distribution: 'adopt'
          java-version: '11'
  
      - name: Read node version from `.nvmrc` file
        id: nvmrc
        shell: bash
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - name: Install required node.js version
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Dependencies
        run: |
          OSCAL_CLI_URL=${{ matrix.cli_url }} && make configure
      - name: Run tests
        shell: bash
        run: |
          make test
      - name : Publish all Junit XML tests results in Github Summary
        uses: test-summary/action@31493c76ec9e7aa675f1585d3ed6f1da69269a86
        if: always()
        with:
            paths: |
              **/reports/junit-*.xml
      