name: Triage Board Management

on:
  issues:
    types:
      - opened
      - reopened
      - transferred

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/add-to-project@5afcf98fcd03f1c2f92c3c83f58ae24323cc57fd
        with:
          project-url: https://github.com/orgs/usnistgov/projects/25
          github-token: ${{ secrets.COMMIT_TOKEN }}
